Add tests for gcp

diff --git a/deploy/gcp/gcp b/deploy/gcp/gcp
--- a/deploy/gcp/gcp
+++ b/deploy/gcp/gcp
@@ -8,6 +8,25 @@
 
 # Usage:
 # ./gcp mygitrepo username@panda.ethz.ch:~/remote-dir
+#
+# TEST: gcp1
+# git init TEST.git
+# echo preved > TEST.git/A
+# (cd TEST.git; git add A; git commit -a -m "Initial import")
+# (cd TEST.git; ur gcp TEST.git ../TEST.deploy.git)
+# cat TEST.deploy.git/TEST.git/A > gcp.out.txt
+# rm -rf TEST.git TEST.deploy.git
+#
+# TEST: gcp2
+# git init TEST.git
+# echo preved > TEST.git/A
+# (cd TEST.git; git add A; git commit -a -m "Initial import")
+# (cd TEST.git; git branch bA ; git checkout bA; git commit -a -m "Branch import")
+# (cd TEST.git; ur gcp TEST.git ../TEST.deploy.git)
+# (cd TEST.deploy.git/TEST.git; git branch) > gcp.out.txt
+# rm -rf TEST.git TEST.deploy.git
+
+set -e
 
 function msg() {
     printf -- "(gcp) $@"  > "/dev/stderr"
@@ -15,7 +34,7 @@ function msg() {
 
 if test $# -ne 2
 then
-   msg "(ERRR) requires two arguments\n"
+   msg "(ERROR) requires two arguments\n"
    exit
 fi
 
@@ -31,8 +50,8 @@ GITFLAGS="--depth 1"
 default_dir=$1
 target=$2
 
-thost=`echo "${target}" | awk -v FS=":" 'NF>1{print $1}'`
-tpath=`echo "${target}" | awk -v FS=":" '    {sub("^[^:]*:", ""); print}'`
+thost=`echo "${target}" | awk -v FS=':' 'NF>1{print $1}'`
+tpath=`echo "${target}" | awk           '{sub("^[^:]*:", ""); print}'`
 
 top=$(${GIT} rev-parse --show-toplevel)
 msg "I think top level git directory is ${top}\n"
@@ -56,7 +75,6 @@ msg "Current branch: %s\n" "${branch}"
     # --depth 1
     git submodule update
 )
-
 
 msg "Create a list of all staged files: %s\n" "${file_list}"
 
@@ -114,3 +132,6 @@ fi
 
 msg "Copying from ${local_target} to ${target}\n"
 "${cpy}" ${cpy_args} -- "${local_target}" "${target}"
+
+# clean up
+rm -rf ${file_list?} ${dir_list?} ${local_target?}
